// BIADemo only
// <copyright file="BiaDemoTestHangfire.cs" company="TheBIADevCompany">
//     Copyright (c) TheBIADevCompany. All rights reserved.
// </copyright>
namespace TheBIADevCompany.BIADemo.Application.Job
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using BIA.Net.Core.Application.Job;
    using BIA.Net.Core.Domain.Dto.Base;
    using BIA.Net.Core.Domain.Dto.Notification;
    using BIA.Net.Core.Domain.Dto.Option;
    using BIA.Net.Core.Domain.RepoContract;
    using Hangfire.Server;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Logging;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;
    using TheBIADevCompany.BIADemo.Crosscutting.Common.Enum;
    using TheBIADevCompany.BIADemo.Domain.NotificationModule.Service;

    /// <summary>
    /// Sample class to use a hangfire task.
    /// </summary>
    public class BiaDemoTestHangfireService : BaseJob, IBiaDemoTestHangfireService
    {
        private readonly INotificationAppService notificationAppService;

        /// <summary>
        /// The signalR Service.
        /// </summary>
        private readonly IClientForHubRepository clientForHubService;

        /// <summary>
        /// Initializes a new instance of the <see cref="BiaDemoTestHangfireService"/> class.
        /// </summary>
        /// <param name="configuration">The configuration.</param>
        /// <param name="logger">logger.</param>
        /// <param name="notificationAppService">The notification service.</param>
        public BiaDemoTestHangfireService(
            IConfiguration configuration,
            ILogger<BiaDemoTestHangfireService> logger,
            INotificationAppService notificationAppService,
            IClientForHubRepository clientForHubService)
            : base(configuration, logger)
        {
            this.notificationAppService = notificationAppService;
            this.clientForHubService = clientForHubService;
        }

        /// <summary>
        /// Run the processes that are waiting.
        /// </summary>
        /// <returns>The <see cref="Task"/> representing the operation to perform.</returns>
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        protected override async Task RunMonitoredTask()
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            await Task.Delay(5000);
            this.Logger.LogInformation($"{DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss")}: BiaDemoTestHangfire => This log is generated by a hangfire task");
        }

        /// <summary>
        /// Test function for run task on hangfire.
        /// </summary>
        /// <returns>The task.</returns>
        public async Task RunLongTask()
        {
            await Task.Delay(5000);
        }

        /// <summary>
        /// Test function for run task on hangfire with notification.
        /// </summary>
        /// <param name="siteId">The current Site Id.</param>
        /// <param name="createdById">The created By.</param>
        /// <param name="context">The context hangfire.</param>
        /// <returns>The task.</returns>
        public async Task RunLongTaskWithNotification(int siteId, int createdById, PerformContext context)
        {
            await Task.Delay(2000);

            var target = new NotificationDataDto
            {
                //Route = new string[] { "examples", "hangfire" },
                Route = new string[] { "examples", "planes", "30" , "edit" }
            };

            var notification = new NotificationDto
            {
                CreatedBy = new OptionDto { Id = createdById },
                CreatedDate = DateTime.Now,
                Description = "notification.success.description",
                SiteId = siteId,
                Title = "notification.success.title",
                //NotifiedPermissions = new List<OptionDto> { new OptionDto { Id = 1, DtoState = DtoState.Added } },
                Read = false,
                JData = JsonConvert.SerializeObject(target, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() }),
            };

            //var notification = new NotificationDto
            //{
            //    CreatedBy = new OptionDto { Id = createdById },
            //    CreatedDate = DateTime.Now,
            //    Description = "notification.success.description",
            //    SiteId = siteId,
            //    Title = "notification.success.title",
            //    NotifiedUsers = new List<OptionDto> { new OptionDto { Id = 2, DtoState = DtoState.Added } },
            //    Read = false,
            //    JData = JsonConvert.SerializeObject(target, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() }),
            //};

            try
            {
                notification.Type = new OptionDto { Id = (int)NotificationType.Task };

                await this.notificationAppService.AddAsync(notification);
            }
            catch (Exception e)
            {
                throw e;
                /*notification.Type = new OptionDto { Id = (int)NotificationType.Error };

                await this.notificationAppService.AddAsync(notification);*/
            }
        }
    }
}