// <auto-generated />

namespace TheBIADevCompany.BIADemo.Infrastructure.Data.Migrations
{
    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class DefaultSite : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsDefault",
                table: "Members",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsDefault",
                table: "Members");
        }
    }
}
