// <auto-generated />

namespace TheBIADevCompany.BIADemo.Infrastructure.Data.Migrations
{

    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class AddViews : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Views",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    TableId = table.Column<string>(maxLength: 100, nullable: false),
                    Name = table.Column<string>(maxLength: 50, nullable: false),
                    Description = table.Column<string>(maxLength: 500, nullable: true),
                    Preference = table.Column<string>(nullable: false),
                    ViewType = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Views", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ViewSite",
                columns: table => new
                {
                    SiteId = table.Column<int>(nullable: false),
                    ViewId = table.Column<int>(nullable: false),
                    IsDefault = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ViewSite", x => new { x.SiteId, x.ViewId });
                    table.ForeignKey(
                        name: "FK_ViewSite_Sites_SiteId",
                        column: x => x.SiteId,
                        principalTable: "Sites",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ViewSite_Views_ViewId",
                        column: x => x.ViewId,
                        principalTable: "Views",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ViewUser",
                columns: table => new
                {
                    UserId = table.Column<int>(nullable: false),
                    ViewId = table.Column<int>(nullable: false),
                    IsDefault = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ViewUser", x => new { x.UserId, x.ViewId });
                    table.ForeignKey(
                        name: "FK_ViewUser_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ViewUser_Views_ViewId",
                        column: x => x.ViewId,
                        principalTable: "Views",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ViewSite_ViewId",
                table: "ViewSite",
                column: "ViewId");

            migrationBuilder.CreateIndex(
                name: "IX_ViewUser_ViewId",
                table: "ViewUser",
                column: "ViewId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ViewSite");

            migrationBuilder.DropTable(
                name: "ViewUser");

            migrationBuilder.DropTable(
                name: "Views");
        }
    }
}
