// <copyright file="BiaErrorMessage.cs" company="BIA">
// Copyright (c) BIA. All rights reserved.
// </copyright>

namespace BIA.Net.Core.Common.Error
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Security.Principal;
    using static BIA.Net.Core.Common.BiaRights;
    using static System.Runtime.InteropServices.JavaScript.JSType;

    /// <summary>
    /// The class containing all the error message with the translations.
    /// </summary>
    public static class BiaErrorMessage
    {
        /// <summary>
        /// List of all custom error translated generated by the back.
        /// </summary>
        private static readonly List<BiaErrorTranslation> Translations = [];

        /// <summary>
        /// Init the BIA error translations.
        /// </summary>
        /// <param name="languageEnglishId">English language id.</param>
        /// <param name="languageFrenchId">French language id.</param>
        /// <param name="languageSpanishId">Spanish language id.</param>
        public static void InitBiaErrorTranslations(int? languageEnglishId = null, int? languageFrenchId = null, int? languageSpanishId = null)
        {
            Translations.Clear();

            static void AddTranslation(int? langId, int errorId, string label)
            {
                if (langId.HasValue)
                {
                    Translations.Add(new BiaErrorTranslation
                    {
                        ErrorId = errorId,
                        LanguageId = langId.Value,
                        Label = label,
                    });
                }
            }

            // InternalServerError
            AddTranslation(languageEnglishId, (int)BiaErrorId.InternalServerError, "An error occurred while processing your request.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.InternalServerError, "Une erreur s'est produite lors du traitement de votre demande.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.InternalServerError, "Se produjo un error al procesar su solicitud.");

            // MemberAlreadyExists
            AddTranslation(languageEnglishId, (int)BiaErrorId.MemberAlreadyExists, "Member already exists.");
            AddTranslation(languageEnglishId, (int)BiaErrorId.MemberAlreadyExists, "Le membre existe déjà.");
            AddTranslation(languageEnglishId, (int)BiaErrorId.MemberAlreadyExists, "El miembro ya existe.");

            // AddEntity
            AddTranslation(languageEnglishId, (int)BiaErrorId.AddEntity, "Unable to add {0}.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.AddEntity, "Impossible d’ajouter {0}.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.AddEntity, "No se puede agregar {0}.");

            // DeleteEntity
            AddTranslation(languageEnglishId, (int)BiaErrorId.DeleteEntity, "Unable to delete {0}.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DeleteEntity, "Impossible de supprimer {0}.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DeleteEntity, "No se puede eliminar {0}.");

            // ModifyEntity
            AddTranslation(languageEnglishId, (int)BiaErrorId.ModifyEntity, "Unable to modify {0}.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.ModifyEntity, "Impossible de modifier {0}.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.ModifyEntity, "No se puede modificar {0}.");

            // ValidationEntity
            AddTranslation(languageEnglishId, (int)BiaErrorId.ValidationEntity, "{0}");
            AddTranslation(languageFrenchId, (int)BiaErrorId.ValidationEntity, "{0}");
            AddTranslation(languageSpanishId, (int)BiaErrorId.ValidationEntity, "{0}");

            // DatabaseForeignKeyConstraint
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseForeignKeyConstraint, "One or many {0} are linked to dependant entities. Ensure to remove all dependant entities first.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseForeignKeyConstraint, "Un ou plusieurs {0} sont liés à des entités dépendantes. Veuillez supprimer toutes les entités dépendantes avant.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseForeignKeyConstraint, "Uno o varios {0} están vinculados a entidades dependientes. Asegúrese de eliminar primero todas las entidades dependientes.");

            // DatabaseUniqueConstraint
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseUniqueConstraint, "An entity {0} already exists with these values.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseUniqueConstraint, "Une entité {0} existe déjà avec ces valeurs.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseUniqueConstraint, "Ya existe una entidad {0} con estos valores.");

            // DatabaseDuplicateKey
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseDuplicateKey, "An entity {0} already exists with these values.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseDuplicateKey, "Une entité {0} existe déjà avec ces valeurs.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseDuplicateKey, "Ya existe una entidad {0} con estos valores.");

            // DatabaseNullValueInsert
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseNullValueInsert, "Field {0} cannot be null in entity {1}.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseNullValueInsert, "Le champ {0} ne peut pas être nul dans l’entité {1}.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseNullValueInsert, "El campo {0} no puede ser nulo en la entidad {1}.");

            // DatabaseLoginUser
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseLoginUser, "Unable to login to the database.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseLoginUser, "Impossible de se connecter à la base de données.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseLoginUser, "No se puede iniciar sesión en la base de datos.");

            // DatabaseOpen
            AddTranslation(languageEnglishId, (int)BiaErrorId.DatabaseOpen, "Unable to open the database.");
            AddTranslation(languageFrenchId, (int)BiaErrorId.DatabaseOpen, "Impossible d’ouvrir la base de données.");
            AddTranslation(languageSpanishId, (int)BiaErrorId.DatabaseOpen, "No se puede abrir la base de datos.");
        }

        /// <summary>
        /// Add range of <see cref="BiaErrorTranslation"/> to current error translations.
        /// </summary>
        /// <param name="translations">The translations.</param>
        public static void AddTranslations(ImmutableList<BiaErrorTranslation> translations)
        {
            Translations.AddRange(translations);
        }

        /// <summary>
        /// Return the translated message for the given <paramref name="errorId"/> from an enum.
        /// </summary>
        /// <typeparam name="TEnum">Error enum type.</typeparam>
        /// <param name="errorId">The error Id.</param>
        /// <param name="languageId">The language Id.</param>
        /// <returns>The translated message.</returns>
        public static string GetMessage<TEnum>(TEnum errorId, int languageId)
            where TEnum : Enum
        {
            return GetMessage(Convert.ToInt32(errorId), languageId);
        }

        /// <summary>
        /// Return the translated message for the given <paramref name="errorId"/>.
        /// </summary>
        /// <typeparam name="TEnum">Error enum type.</typeparam>
        /// <param name="errorId">The error Id.</param>
        /// <param name="languageId">The language Id.</param>
        /// <returns>The translated message.</returns>
        public static string GetMessage(int errorId, int languageId)
        {
            return Translations.Find(t => t.ErrorId == errorId && t.LanguageId == languageId)?.Label;
        }
    }
}