// <copyright file="ErrorMessage.cs" company="TheBIADevCompany">
// Copyright (c) TheBIADevCompany. All rights reserved.
// </copyright>

namespace TheBIADevCompany.BIADemo.Crosscutting.Common.Error
{
    using System.Collections.Immutable;
    using BIA.Net.Core.Common.Error;
    using static TheBIADevCompany.BIADemo.Crosscutting.Common.Constants;

    /// <summary>
    /// The class containing all constants.
    /// </summary>
    public static class ErrorMessage
    {
        /// <summary>
        /// List of all custom error translated generated by the back.
        /// </summary>
        private static readonly ImmutableList<BiaErrorTranslation> Translations =
        [
            // Begin BIADemo
            new BiaErrorTranslation() { ErrorId = (int)ErrorId.HangfireHandledError, LanguageId = LanguageId.English, Label = "Example message of a handled error." },
            new BiaErrorTranslation() { ErrorId = (int)ErrorId.HangfireHandledError, LanguageId = LanguageId.French, Label = "Message d’exemple d’une erreur gérée." },
            new BiaErrorTranslation() { ErrorId = (int)ErrorId.HangfireHandledError, LanguageId = LanguageId.Spanish, Label = "Mensaje de ejemplo de un error controlado." },

            // End BIADemo

            // Begin project error messages

            // End project error messages
        ];

        /// <summary>
        /// Fill the error translations.
        /// </summary>
        public static void FillErrorTranslations()
        {
            BiaErrorMessage.InitBiaErrorTranslations(LanguageId.English, LanguageId.French, LanguageId.Spanish);
            BiaErrorMessage.MergeTranslations(Translations);
        }
    }
}